---
- name: Install packages
  become: true
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python-pip

- name: Add docker apt key
  become: true
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- set_fact: arch=armhf
  when: ansible_machine == "armv7l"

- set_fact: arch=amd64
  when: ansible_machine == "x86_64"

- name: Add apt repository for docker
  become: true
  apt_repository:
      repo: "deb [arch={{arch}}] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
      state: present

- name: Install docker
  become: true
  apt: name="{{item}}"
  with_items:
      - docker-ce 

- name: Don't have docker-compose from apt
  become: true
  apt: name=docker-compose state=absent
