---
- name: abcd
  debug: msg=hello

- name: Install for debian
  when: ansible_os_family == "Debian"
  become: yes
  include: debian.yml

- name: Install for redhat
  when: ansible_os_family == "RedHat"
  become: yes
  include: redhat.yml

- name: Add user to docker group
  become: yes
  user: name="{{ansible_user_id}}"
        groups=docker
        append=yes

- name: Install python packages
  become: yes
  pip: name=docker-py state=present

- name: Do have docker-compose from pip
  become: true
  pip: name=docker-compose state=present
