---
- name: Install for debian
  when: ansible_os_family == "Debian"
  become: yes
  include: debian.yml

- name: Install for redhat
  when: ansible_os_family == "RedHat"
  become: yes
  include: redhat.yml

- name: Add user to docker group
  become: yes
  user: name="{{ansible_user}}"
        groups=docker
        append=yes

- name: Install python packages
  become: yes
  pip: name=docker-py version=1.7.0 state=present
