---
- name: Run distro specific tasks
  become: true
  include_tasks: "{{ansible_os_family|lower}}.yml"

- name: Add user to docker group
  become: yes
  user: name="{{ansible_user_id}}"
        groups=docker
        append=yes

- name: Install python packages
  become: yes
  pip: name=docker state=present

- name: Do have docker-compose from pip
  become: true
  pip: name=docker-compose state=present
