---
- name: Add yum repository for docker
  become: true
  yum_repository: name=docker
                  description="Docker yum repository"
                  gpgkey=https://yum.dockerproject.org/gpg
                  baseurl="https://yum.dockerproject.org/repo/main/{{ansible_distribution|lower}}/{{ansible_distribution_major_version}}"

- name: Install packages
  become: true
  yum:
      update_cache: yes
      name:
      - epel-release
      - docker-engine
      - python-pip

- name: Start docker engine at boot
  become: true
  systemd: name=docker enabled=yes state=started
